global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'postgres_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9187']
  
  # - job_name: 'nodeexporter'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['nodeexporter:9100']
